name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: copy artifacts
      run: |
        rm -rf downloads
        mkdir downloads
        cp target/release/rust_test downloads/
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: downloads      
